---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "hub-manager.clusterRoleName" . }}
  labels:
    {{- include "hub-manager.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "hub-manager.clusterRoleName" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "hub-manager.serviceAccountName" . }}
    namespace: {{ include "hub-manager.namespace" . }}
