---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "hub-manager.fullname" $ }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "hub-manager.labels" $ | nindent 4 }}
rules:
  - apiGroups:
      - ""
    resources:
      - services
      - endpoints
      - pods
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - ""
    resources:
      - secrets
    verbs:
      - get
      - list
      - watch
      - update
      - create
      - delete
  - apiGroups:
      - coordination.k8s.io
    resources:
      - leases
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete
  - apiGroups:
      - hub.traefik.io
    resources:
      - aiservices
    verbs:
      - get
      - list
      - watch
