---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "hub-manager.fullname" $ }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "hub-manager.labels" $ | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "hub-manager.fullname" $ }}
subjects:
  - kind: ServiceAccount
    name: {{ include "hub-manager.fullname" $ }}
    namespace: {{ .Release.Namespace }}
