{{- if not .Values.serviceAccount.name -}}
kind: ServiceAccount
apiVersion: v1
metadata:
  name: {{ include "hub-manager.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "hub-manager.labels" . | nindent 4 }}
  annotations:
  {{- with .Values.serviceAccount.annotations }}
  {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: {{ .Values.serviceAccount.automountServiceAccountToken }}
{{- end -}}
