{{- if not .Values.serviceAccount.name -}}
kind: ServiceAccount
apiVersion: v1
metadata:
  name: {{ include "hub-manager.serviceAccountName" . }}
  namespace: {{ include "hub-manager.namespace" . }}
  labels:
    {{- include "hub-manager.labels" . | nindent 4 }}
  annotations:
  {{- with .Values.serviceAccount.annotations }}
  {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: false
{{- end -}}
