apiVersion: v2
name: traefik
description: A Traefik based Kubernetes ingress controller
type: application
version: 40.0.0-ea.3
# renovate: image=traefik
appVersion: v3.7.0-rc.2
kubeVersion: ">=1.25.0-0"
keywords:
  - traefik
  - ingress
  - networking
home: https://traefik.io/
sources:
  - https://github.com/traefik/traefik-helm-chart
  - https://github.com/traefik/traefik
maintainers:
  - name: mloiseleur
    email: michel.loiseleur@traefik.io
  - name: darkweaver87
    email: remi.buisson@traefik.io
  - name: jnoordsij
icon: https://raw.githubusercontent.com/traefik/traefik/master/docs/content/assets/img/traefik.logo.png
annotations:
  traefik.io/proxy-min-version: v3.6.0
  traefik.io/proxy-max-version: v3.7.0-rc.2
  traefik.io/hub-min-version: v3.19.3
  traefik.io/hub-max-version: v3.20.0-rc.1
  artifacthub.io/changes: |
    - "feat: 🚀 upgrade traefik to v3.7.0-ea.3"
    - "chore(release): 🚀 publish v40.0.0-ea.3"
