# Default values for Hub-platform
# This is a YAML-formatted file
# Declare variables to be passed into templates

image:  # @schema additionalProperties: false
  # -- Hub-manager image host registry
  registry: gcr.io
  # -- Hub-manager image repository
  repository: traefiklabs/hub-manager
  # -- defaults to appVersion. It's used for version checking, even prefixed with experimental- or latest-
  tag:  # @schema type:[string, null]
  # -- Traefik image pull policy
  pullPolicy: IfNotPresent

# -- Address to listen on
address: ":80"

logs:
  # -- Set logs format
  format: "json" # @schema enum:["common", "json", null]; type:[string, null]; default: "common"
  # By default, the level is set to INFO
  # -- Alternative logging levels are TRACE, DEBUG, INFO, WARN, ERROR, FATAL, and PANIC
  level: "INFO"  # @schema enum:[TRACE,DEBUG,INFO,WARN,ERROR,FATAL,PANIC]; default: "INFO"

deployment:
  # -- Number of pods of the deployment
  replicas: 1
  # -- Number of old history to retain to allow rollback (If not set, default Kubernetes value is set to 10)
  revisionHistoryLimit: 10  # @schema type:[integer, null];minimum:0
  # -- Amount of time (in seconds) before Kubernetes will send the SIGKILL signal if shut down does not happen
  terminationGracePeriodSeconds: 60
  # -- Additional deployment annotations
  annotations: {}
  # -- Additional deployment labels (e.g. for filtering deployment by custom labels)
  labels: {}
  # -- Additional pod annotations (e.g. for mesh injection or prometheus scraping)
  podAnnotations: {}
  # -- Additional Pod labels (e.g. for filtering Pod by custom labels)
  podLabels: {}
  # -- Pull secret for fetching container image
  imagePullSecrets: []
  # -- Pod lifecycle actions
  lifecycle: {}

updateStrategy:  # @schema additionalProperties: false
  # -- Customize updateStrategy of Deployment
  type: RollingUpdate
  rollingUpdate:
    maxUnavailable: 0  # @schema type:[integer, string, null]
    maxSurge: 1        # @schema type:[integer, string, null]

# This section builds out the service account more information can be found here: https://kubernetes.io/docs/concepts/security/service-accounts/
serviceAccount:
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""
  # -- Whether to automatically mount a ServiceAccount's API credentials
  automount: true
  # -- Additional serviceAccount annotations (e.g. for oidc authentication)
  annotations: {}

# This is for setting up a service more information can be found here: https://kubernetes.io/docs/concepts/services-networking/service/
service:
  enabled: true
  # This sets the service type more information can be found here: https://kubernetes.io/docs/concepts/services-networking/service/#publishing-services-service-types
  type: ClusterIP
  # This sets the ports more information can be found here: https://kubernetes.io/docs/concepts/services-networking/service/#field-spec-ports
  port: 80
  # -- Additional annotations
  annotations: {}

autoscaling:  # @schema additionalProperties: false
  # -- Create HorizontalPodAutoscaler object
  enabled: false
  # -- minReplicas is the lower limit for the number of replicas to which the autoscaler can scale down. It defaults to 1 pod
  minReplicas:  # @schema type:[integer, null]; minimum:0
  # -- maxReplicas is the upper limit for the number of pods that can be set by the autoscaler; cannot be smaller than MinReplicas
  maxReplicas:  # @schema type:[integer, null]; minimum:0
  # -- metrics contains the specifications for which to use to calculate the desired replica count (the maximum replica count across all metrics will be used)
  metrics: []
  # -- behavior configures the scaling behavior of the target in both Up and Down directions (scaleUp and scaleDown fields respectively)
  behavior: {}
  # -- scaleTargetRef points to the target resource to scale, and is used for the pods for which metrics should be collected, as well as to actually change the replica count
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: "{{ template \"hub-platform.fullname\" . }}"

# This block is for setting up the ingress for more information can be found here: https://kubernetes.io/docs/concepts/services-networking/ingress/
ingressRoute:
  enabled: false
  # -- Additional ingressRoute annotations (e.g. for kubernetes.io/ingress.class)
  annotations: {}
  # -- Additional ingressRoute labels (e.g. for filtering IngressRoute by custom labels)
  labels: {}
  # -- Specify the allowed entrypoints to use for the ingress route
  entryPoints: ["websecure"]
  # -- Routes
  routes: []
    # - match: >-
    #   Host(`foo.bar.com`) && (
    #   PathPrefix(`/foo/bar`) ||
    #   PathPrefix(`/foo/baz`)
    #   )
    # middlewares:
    #   - name: foo
    # services:
    #   - name: bar
    #     port: 80
  # -- TLS options (e.g. secret containing certificate)
  tls: {}
  #  - secretName: chart-example-tls

# -- [Resources](https://kubernetes.io/docs/concepts/configuration/manage-resources-containers/) for `traefik` container
resources: {}

affinity: {}

# -- nodeSelector is the simplest recommended form of node selection constraint
nodeSelector: {}

# -- Tolerations allow the scheduler to schedule pods with matching taints
tolerations: []

# -- [SecurityContext](https://kubernetes.io/docs/reference/kubernetes-api/workload-resources/pod-v1/#security-context-1)
# @default -- See _values.yaml_
securityContext:
  allowPrivilegeEscalation: false
  readOnlyRootFilesystem: true
  runAsUser: 65534
  runAsGroup: 65534
  seccompProfile:
    type: RuntimeDefault
  capabilities:
    drop:
      - NET_RAW

readinessProbe:  # @schema additionalProperties: false
  httpGet:
    path: /ready
    port: 8080
  # -- The number of consecutive failures allowed before considering the probe as failed
  failureThreshold: 2
  # -- The number of seconds to wait between consecutive probes
  periodSeconds: 5
  # -- The number of seconds to wait before starting the first probe
  initialDelaySeconds: 5

livenessProbe:  # @schema additionalProperties: false
  httpGet:
    path: /live
    port: 8080
  # -- The number of consecutive failures allowed before considering the probe as failed
  failureThreshold: 2
  # -- The number of seconds to wait before starting the first probe
  initialDelaySeconds: 5
  # -- The number of seconds to wait between consecutive probes
  periodSeconds: 5

# -- Define [Startup Probe](https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes/#define-startup-probes)
startupProbe: {}

postgres:
  # -- Name of Secret with key 'postgres-uri' set to a valid Postgres connection string
  uri: ""

mongodb:
  # -- Name of Secret with key 'mongodb-uri' set to a valid MongoDB connection string
  uri: ""
  # -- MongoDB minimum pool size
  minPool: 10
  # -- MongoDB maximum pool size
  maxPool: 30
  # -- Name of Secret with key 'mongodb-encryption-key' set to a valid encryption key
  encryptionKey: ""

mq:
  # -- URL of the NATS message queue
  url: ""
  # -- Path to user credential file to use on NATs message queue
  credsFile: ""
  # -- Time to wait before re-processing a NAK message
  delay: 1
  idp:
    # -- IDP stream name
    streamName: "idps"
    # -- IDP consumer durable name on the IDP stream
    consumerName: "hub-api-management-idp"
    # -- Portal consumer durable name on the IDP stream
    portalName: "hub-api-management-portal"
  workspace:
    # -- Workspaces stream name
    streamName: "workspaces"
    # -- Consumer durable name on the workspace stream
    consumerName: "hub-api-management"

jwt:
  # -- Name of Secret with key 'jwt-iss' set to a valid JWT Issuer
  iss: ""
  # -- Name of Secret with key 'jwt-sub' set to a valid JWT Sub
  sub: ""
  # -- Name of Secret with key 'jwt-cert' set to a valid JWT Cert
  cert: ""

services:
  # -- Base URL of the offer service
  offerURL: ""
  # -- Base URL of the workspace service
  workspaceURL: ""
  # -- URL of the trace service
  traceURL: ""

hydra:
  # -- URL of the Hydra admin API
  url: ""
  # -- URL of the Hydra issuer
  issuerURL: ""

tracing:
  # -- Address to send traces
  address: ""
  # -- use HTTP instead of HTTPS
  insecure: false
  # -- Probability to send traces
  probability: 0
  # -- Username to connect to tracing address
  username: ""
  # -- Name of Secret with key 'tracing-password' set to a valid password
  password: ""

ports:
  # @schema additionalProperties: false
  http:
    port: 8080
    # -- The port protocol (TCP/UDP)
    protocol: TCP
  
# -- overrides the app.kubernetes.io/name label
nameOverride: ""

# -- Overrides the resource name for templates (i.e deployment, service, etc..)
fullnameOverride: ""

# -- This field overrides the default Release Namespace for Helm
namespaceOverride: ""
