{{- if .Values.autoscaling.enabled }}

{{- if not .Values.autoscaling.maxReplicas }}
  {{- fail "ERROR: maxReplicas is required on HPA" }}
{{- end }}

apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "hub-manager.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "hub-manager.labels" . | nindent 4 }}
spec:
  {{- tpl (toYaml .Values.autoscaling.spec) . | nindent 2 }}
{{- end }}
