{{- if .Values.service.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "hub-manager.fullname" . }}
  namespace: {{ .Release.Namespace . }}
  labels:
    {{- include "hub-platform.labels" . | nindent 4 }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "hub-platform.selectorLabels" . | nindent 4 }}
{{- end }}