{{- $version := include "traefik.proxyVersion" $ }}
{{- $proxyMinVersion := index .Chart.Annotations "traefik.io/proxy-min-version" }}
{{- $proxyMaxVersion := index .Chart.Annotations "traefik.io/proxy-max-version" }}
{{- if (ne $version "experimental-v3.0") }}
  {{- if (semverCompare (printf "<%s-0" $proxyMinVersion) $version) }}
    {{- fail (printf "ERROR: This version of the Chart only supports Traefik Proxy %s+" $proxyMinVersion) -}}
  {{- end }}
  {{- if and (eq (include "traefik.isStableVersion" $version) "true") (semverCompare (printf ">%s" $proxyMaxVersion) $version) }}
    {{- fail (printf "ERROR: This version of the Chart only supports Traefik Proxy up to %s." $proxyMaxVersion) -}}
  {{- end }}
{{- end }}

{{- if and .Values.hub.enabled (not (contains "traefik-hub" .Values.image.repository)) }}
  {{- fail "ERROR: traefik-hub image is required when enabling Traefik Hub" -}}
{{- end }}

{{- if and (.Values.providers.knative).enabled (not .Values.experimental.knative) }}
  {{- fail "ERROR: Knative is experimental. Enable it by setting experimental.knative to true" -}}
{{- end }}

{{- if and (.Values.providers.kubernetesGateway.enabled) (.Values.gateway.defaultScope) (not .Values.providers.kubernetesGateway.experimentalChannel) }}
  {{- fail "ERROR: The Gateway 'defaultScope' field is experimental. Enable it by setting providers.kubernetesGateway.experimentalChannel=true" }}
{{- end }}

{{- if .Values.rbac.namespaced }}
  {{- if .Values.providers.kubernetesGateway.enabled }}
    {{- fail "ERROR: Kubernetes Gateway provider requires ClusterRole. RBAC cannot be namespaced." }}
  {{- end }}
  {{- if and (not .Values.providers.kubernetesIngress.enabled) (not .Values.providers.kubernetesCRD.enabled) }}
    {{- fail "ERROR: namespaced rbac requires Kubernetes CRD or Kubernetes Ingress provider." }}
  {{- end }}
{{- end }}

{{- if and (semverCompare "<v3.6.2-0" $version) (.Values.providers.kubernetesIngressNGINX).enabled}}
  {{- fail "ERROR: Kubernetes Ingress NGINX provider is only available for traefik >= v3.6.2." }}
{{- end }}

{{- if and (.Values.providers.kubernetesIngressNGINX.modsec).enabled (not $.Values.hub.token) }}
  {{- fail "ERROR: Kubernetes Ingress NGINX provider modsec option requires Traefik Hub." }}
{{- end }}

{{- with .Values.providers.kubernetesIngressNGINX }}
  {{- if and (semverCompare "<v3.7.0-0" $version) .enabled (or
    (ne .proxyRequestBuffering nil)
    (gt (.clientBodyBufferSize | int) 0)
    (gt (.proxyBodySize | int) 0)
    (ne .proxyBuffering nil)
    (gt (.proxyBufferSize | int) 0)
    (gt (.proxyBuffersNumber | int) 0)
    (gt (.proxyConnectTimeout | int) 0)
    (gt (.proxyReadTimeout | int) 0)
    (gt (.proxySendTimeout | int) 0)
    (not (empty .proxyNextUpstream))
    (gt (.proxyNextUpstreamTries | int) 0)
    (gt (.proxyNextUpstreamTimeout | int) 0)
    (not (empty .customHTTPErrors))
    (gt (.upstreamKeepaliveTimeout | int) 0)
    (ne .allowCrossNamespaceResources nil)
    (not (empty .globalAllowedResponseHeaders))
    (ne .allowSnippetAnnotations nil)
    (not (empty .httpEntryPoint))
    (not (empty .httpsEntryPoint)) )}}
    {{- fail "ERROR: some Kubernetes Ingress NGINX provider options require traefik >= v3.7.0." }}
  {{- end }}
{{- end }}

{{- if and (semverCompare "<v3.7.0-ea.2" $version) (ne (.Values.providers.kubernetesIngressNGINX).strictValidatePathType nil) }}
  {{- fail "ERROR: Kubernetes Ingress NGINX provider strictValidatePathType option requires traefik >= v3.7.0-ea.2." }}
{{- end }}

{{- if and (semverCompare "<v3.7.0-rc.1" $version) (not (empty .Values.providers.precedence)) }}
  {{- fail "ERROR: providers.precedence option requires traefik >= v3.7.0-rc.1." }}
{{- end }}

{{- if and (semverCompare "<v3.7.0-rc.1" $version) (not (empty (.Values.providers.kubernetesIngressNGINX).globalAuthUrl)) }}
  {{- fail "ERROR: Kubernetes Ingress NGINX provider globalAuthUrl option requires traefik >= v3.7.0-rc.1." }}
{{- end }}

{{- if and (not .Values.experimental.otlpLogs) (or (.Values.logs.general.otlp.enabled) (.Values.logs.access.otlp.enabled))}}
  {{- fail "ERROR: otlp on logs or access logs is an experimental feature and needs experimental.otlpLogs=true." }}
{{- end }}

{{- if and (semverCompare "<v3.7.0-0" $version) .Values.logs.access.dualOutput }}
  {{- fail "ERROR: accesslog.dualOutput is only available for traefik >= v3.7.0." }}
{{- end }}

{{- if and (semverCompare "<v3.7.0-0" $version) .Values.global.notAppendXForwardedFor }}
  {{- fail "ERROR: global.notAppendXForwardedFor is only available for traefik >= v3.7.0." }}
{{- end }}

{{- range $name, $config := .Values.ports }}
  {{- if and $config (($config.forwardedHeaders).notAppendXForwardedFor) (semverCompare "<v3.7.0-0" $version) }}
  {{- fail "ERROR: forwardedHeaders.notAppendXForwardedFor is only available for traefik >= v3.7.0." }}
  {{- end }}
  {{- if and $config.uplink (empty $.Values.hub.token) }}
    {{ fail "ERROR: uplink EntryPoints can only be used with Traefik Hub" }}
  {{- end }}
{{- end }}

{{- if and (semverCompare "<v3.6.4-0" $version) (or
    (eq .Values.ports.websecure.http.sanitizePath false)
    .Values.ports.websecure.http.encodedCharacters.allowEncodedSlash
    .Values.ports.websecure.http.encodedCharacters.allowEncodedBackSlash
    .Values.ports.websecure.http.encodedCharacters.allowEncodedNullCharacter
    .Values.ports.websecure.http.encodedCharacters.allowEncodedSemicolon
    .Values.ports.websecure.http.encodedCharacters.allowEncodedPercent
    .Values.ports.websecure.http.encodedCharacters.allowEncodedQuestionMark
    .Values.ports.websecure.http.encodedCharacters.allowEncodedHash )}}
  {{- fail "ERROR: request path security options are only available for traefik >= v3.6.4." }}
{{- end }}

{{- if $.Values.hub.token -}}
  {{ $hubVersion := $.Values.oci_meta.enabled | ternary $.Values.oci_meta.images.hub.tag $.Values.image.tag }}
  {{ $hubVersion = ($.Values.global.azure.enabled | ternary $.Values.global.azure.images.hub.tag $hubVersion) }}
  {{- if and (not $hubVersion) $.Values.versionOverride }}
    {{- $hubVersion = $.Values.versionOverride }}
  {{- end }}
  {{ if not $hubVersion }}
    {{ fail "When using Traefik Hub, image.tag must be set, or image.digest with versionOverride." }}
  {{- end -}}

  {{ $hubVersion = (split "@" (default "v3" $hubVersion))._0 }}

  {{/* Consider non semver versions as latest one  */}}
  {{- if not (regexMatch "v[0-9]+.[0-9]+.[0-9]+" (default "" $hubVersion)) -}}
    {{ $hubVersion = "v3.99" }}
  {{- end }}

  {{- $hubMinVersion := index $.Chart.Annotations "traefik.io/hub-min-version" }}
  {{- $hubMaxVersion := index $.Chart.Annotations "traefik.io/hub-max-version" }}
  {{- if semverCompare (printf "<%s-0" $hubMinVersion) $hubVersion }}
    {{ fail (printf "ERROR: this Chart supports *only* Traefik Hub >= %s." $hubMinVersion) }}
  {{- end }}
  {{- if and (eq (include "traefik.isStableVersion" $hubVersion) "true") (semverCompare (printf ">%s" $hubMaxVersion) $hubVersion) }}
    {{ fail (printf "ERROR: this Chart only supports Traefik Hub up to %s." $hubMaxVersion) }}
  {{- end }}

  {{- if and (not $.Values.tracing.otlp.enabled) .Values.hub.tracing.additionalTraceHeaders.enabled }}
    {{ fail "ERROR: additionalTraceHeaders needs tracing.otlp to be enabled."}}
  {{- end }}

  {{- with .Values.hub.pluginRegistry.sources }}
    {{- range $pluginName, $pluginConf := . }}
      {{- if not (hasKey $.Values.experimental.plugins $pluginName) }}
         {{ fail (printf "ERROR: pluginRegistry source %s is not used in experimental.plugins." $pluginName) }}
      {{- end }}
    {{- end }}
  {{- end }}

  {{- range $portName, $config := .Values.ports }}
    {{- if $config.uplink }}
      {{- if semverCompare "<v3.20.0-0" $hubVersion }}
        {{ fail "ERROR: uplink is a feature only available for Traefik Hub >= v3.20.0."}}
      {{- end }}
      {{- if (not $.Values.hub.providers.multicluster.enabled) }}
        {{ fail "ERROR: uplink EntryPoints requires the hub multicluster provider" }}
      {{- end }}
    {{- end }}
  {{- end }}

  {{- if and (.Values.providers.kubernetesIngressNGINX.modsec).enabled (semverCompare "<v3.20.0-ea.8" $hubVersion) }}
    {{ fail "ERROR: Kubernetes Ingress NGINX provider modsec option requires Traefik Hub >= v3.20.0-ea.8." }}
  {{- end }}

  {{- if and $.Values.hub.providers.multicluster.enabled (semverCompare "<v3.20.0-ea.1" $hubVersion) }}
    {{ fail "ERROR: hub.providers.multicluster is only available for Traefik Hub >= v3.20.0-ea.1." }}
  {{- end }}

  {{- if semverCompare "<v3.20.0-ea.7" $hubVersion }}
    {{- range $childName, $childConfig := $.Values.hub.providers.multicluster.children }}
      {{- if or (($childConfig.serversTransport).forwardingTimeouts).readTimeout (($childConfig.serversTransport).forwardingTimeouts).writeTimeout }}
        {{ fail "ERROR: hub.providers.multicluster.children.<name>.serversTransport.forwardingTimeouts.readTimeout and .writeTimeout are only available for Traefik Hub >= v3.20.0-ea.7." }}
      {{- end }}
    {{- end }}
  {{- end }}

  {{- if and $.Values.hub.providers.nutanixPrismCentral.enabled (semverCompare "<v3.20.0-ea.1" $hubVersion) }}
    {{ fail "ERROR: hub.providers.nutanixPrismCentral is only available for Traefik Hub >= v3.20.0-ea.1." }}
  {{- end }}

{{- end }}
