{{- $entry := index (.Values.secret | default dict) "hub-license" -}}
{{- if and (kindIs "map" $entry) (include "traefik.hubTokenInline" .) -}}
apiVersion: v1
kind: Secret
metadata:
  {{- include "traefik.objectMeta" (dict "ctx" . "name" (printf "%s-hub-license" (include "traefik.fullname" .)) "namespace" (include "traefik.namespace" .) "userMetadata" ($entry.metadata | default dict)) | nindent 2 }}
type: Opaque
data:
  token: {{ include "traefik.hubTokenInline" . | b64enc | quote }}
{{- end -}}
