{{- range $name, $entry := (.Values.tlsStore | default dict) }}
{{- $entry = $entry | default dict }}
---
apiVersion: traefik.io/v1alpha1
kind: TLSStore
metadata:
  {{- include "traefik.objectMeta" (dict
      "ctx" $
      "name" $name
      "namespace" (include "traefik.namespace" $)
      "userMetadata" ($entry.metadata | default dict)
  ) | nindent 2 }}
spec:
  {{- toYaml ($entry.spec | default dict) | nindent 2 }}
{{- end }}
