---
name: Test

on:
  workflow_call:
  workflow_dispatch:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: 0

      - name: Checkout master
        run: git checkout master && git checkout - && git rev-parse HEAD

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Check traefik if values schema is up-to-date
        uses: losisin/helm-values-schema-json-action@39cdf80504f6c95ad3c4f317e2135e2509ea56bb # v3.0.0
        with:
          working-directory: traefik
          fail-on-diff: true
          useHelmDocs: true

      - name: Lint Chart
        run: make lint

      - name: Install Helm
        uses: azure/setup-helm@dda3372f752e03dde6b3237bc9431cdc2f7a02a2 # v5.0.0
        with:
          # renovate: datasource=github-releases depName=helm/helm
          version: v3.19.0

      - name: Install helm-unittest plugin
        env:
          # renovate: datasource=github-releases depName=helm-unittest/helm-unittest
          HELM_UNITTEST_VERSION: 1.0.1
        run: helm plugin install https://github.com/helm-unittest/helm-unittest --version "$HELM_UNITTEST_VERSION"

      - name: Test Chart
        run: make test

      - name: Test overrideNamespace
        run: make test-ns

      - name: Test CRDs consistency
        run: make test-crds-consistency

      - name: Test if it's a release PR
        id: check
        run: |
          set +e
          changed=$(git diff --name-only -r HEAD^1 HEAD | grep Chart.yaml)
          if [[ -n $changed ]] ; then
            echo "release=true" >> "$GITHUB_OUTPUT"
          fi
          set -e

      - name: Check docs
        run: |
          set +e
          make docs
          changed=$(git status | grep VALUES.md)
          if [[ -n $changed ]]; then
            echo "Traefik values have changed. Run make docs"
            git diff
            exit 1
          fi
          set -e
          exit 0

      - name: Lint markdown
        uses: nosborn/github-action-markdown-cli@508d6cefd8f0cc99eab5d2d4685b1d5f470042c1 # v3.5.0
        with:
          files: "{EXAMPLES,README,CONTRIBUTING}.md"
          config_file: .markdownlint.json

      - name: Create kind cluster
        if: steps.check.outputs.release
        uses: helm/kind-action@ef37e7f390d99f746eb8b610417061a60e82a6cc # v1.14.0

      - name: Install LB on Kind
        if: steps.check.outputs.release
        run: |
          kubectl apply -f https://raw.githubusercontent.com/metallb/metallb/v0.13.11/config/manifests/metallb-native.yaml
          kubectl wait --namespace metallb-system --for=condition=ready pod --selector=app=metallb --timeout=90s
          kubectl apply -f hack/metallb-config.yaml

      - name: Check install on Kind (standard)
        if: steps.check.outputs.release
        run: |
          make test-install

      - name: Check install on Kind (with CRDS)
        if: steps.check.outputs.release
        run: |
          make test-install-with-crds
